/* framework tables */
CREATE DATABASE IF NOT EXISTS `pdi_logging` DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS `pdi_control` DEFAULT CHARACTER SET utf8;



DROP TABLE IF EXISTS pdi_control.job_control;
CREATE TABLE pdi_control.job_control (
	batch_id int4 NULL,
	jobname varchar(124) NULL,
	work_unit varchar(124) NULL,
	status varchar(32) NULL,
	project varchar(64) NULL,
	starttime datetime NULL,
	logtime datetime NULL,
	ip_address text NULL,
	hostname text NULL,
	pid int4 NULL
)
;

grant all on pdi_control.* to 'postgres'@'localhost' identified by 'password';

DROP TABLE IF EXISTS pdi_logging.log_channel;
CREATE TABLE pdi_logging.log_channel
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE DATETIME
, LOGGING_OBJECT_TYPE VARCHAR(255)
, OBJECT_NAME VARCHAR(255)
, OBJECT_COPY VARCHAR(255)
, REPOSITORY_DIRECTORY VARCHAR(255)
, FILENAME VARCHAR(255)
, OBJECT_ID VARCHAR(255)
, OBJECT_REVISION VARCHAR(255)
, PARENT_CHANNEL_ID VARCHAR(255)
, ROOT_CHANNEL_ID VARCHAR(255)
)
;



DROP TABLE IF EXISTS pdi_logging.log_job; 
CREATE TABLE pdi_logging.log_job
(
  ID_JOB INTEGER
, CHANNEL_ID VARCHAR(255)
, JOBNAME VARCHAR(255)
, `STATUS` VARCHAR(15)
, LINES_READ BIGINT(38)
, LINES_WRITTEN BIGINT(38)
, LINES_UPDATED BIGINT(38)
, LINES_INPUT BIGINT(38)
, LINES_OUTPUT BIGINT(38)
, LINES_REJECTED BIGINT(38)
, `ERRORS` BIGINT(38)
, STARTDATE DATETIME
, ENDDATE DATETIME
, LOGDATE DATETIME
, DEPDATE DATETIME
, REPLAYDATE DATETIME
, LOG_FIELD LONGTEXT
, EXECUTING_SERVER VARCHAR(255)
, EXECUTING_USER VARCHAR(255)
, START_JOB_ENTRY VARCHAR(255)
, `CLIENT` VARCHAR(255)
)
;
CREATE INDEX IDX_job_logs_1 ON pdi_logging.log_job(ID_JOB)
;
CREATE INDEX IDX_job_logs_2 ON pdi_logging.log_job(ERRORS, STATUS, JOBNAME)
;

DROP TABLE IF EXISTS pdi_logging.log_tran;
CREATE TABLE pdi_logging.log_tran
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, TRANSNAME VARCHAR(255)
, `STATUS` VARCHAR(15)
, LINES_READ BIGINT(38)
, LINES_WRITTEN BIGINT(38)
, LINES_UPDATED BIGINT(38)
, LINES_INPUT BIGINT(38)
, LINES_OUTPUT BIGINT(38)
, LINES_REJECTED BIGINT(38)
, `ERRORS` BIGINT(38)
, STARTDATE DATETIME
, ENDDATE DATETIME
, LOGDATE DATETIME
, DEPDATE DATETIME
, REPLAYDATE DATETIME
, LOG_FIELD LONGTEXT
, EXECUTING_SERVER VARCHAR(255)
, EXECUTING_USER VARCHAR(255)
, `CLIENT` VARCHAR(255)
)
;
CREATE INDEX IDX_trans_logs_1 ON pdi_logging.log_tran(ID_BATCH)
;
CREATE INDEX IDX_trans_logs_2 ON pdi_logging.log_tran(ERRORS, STATUS, TRANSNAME)
;
grant all on pdi_logging.* to 'postgres'@'localhost' identified by 'password';

/* framework demo tables */
CREATE SCHEMA sales_dwh AUTHORIZATION postgres;

